name: bsuir_schedule
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Только здесь указываем зависимость
    sdk: flutter
  get_it: ^8.0.3
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dartz: ^0.10.1
  http: ^1.4.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  injectable: ^2.5.1
  shared_preferences: ^2.5.3
  internet_connection_checker: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0  # Добавьте обратно

flutter:
  uses-material-design: true
  generate: true  # Включаем генерацию кода
  # assets:
  # Добавьте сюда ваши asset-ы если есть
  # - assets/images/
